version: '3.8'
services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
volumes:
  pgdata:
